### ISSUE TITLE
Public License?

### ISSUE THREAD

**Issue by okfineIGitIt** [koltenfluckiger/com.koltenfluckiger.streamdeck-python-plugin.sdPlugin#2]
Hi @koltenfluckiger ! I'm interested in using your code for my work, need to make custom python stream deck plugin. I'd like to fork your code and remove all functionality for running python scripts, leaving only the file with the `Plugin` class and dunder main code (as well as the other files needed for Stream Deck plugins). I would also add instructions for others who are interested in building custom Stream Deck plugins in Python.

I noticed that you haven't explicitly added an open source license to this code, and was wondering if you would be open to doing so? It would be a big help!

**Comment by koltenfluckiger** [comment]
Added license to master

**Comment by okfineIGitIt** [comment]
> Added license to master

Thanks!
